name: CI/CD Django App

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: rdxnareshpatel/django-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with short SHA tag
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:$SHORT_SHA
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl set image deployment/django-app django=$IMAGE_NAME:$SHORT_SHA
        echo "✅ CI/CD working! New version deployed: $IMAGE_NAME:$SHORT_SHA"
