name: CI Django App

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: rdxnareshpatel/django-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image with short SHA tag
      id: build_push
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:$SHORT_SHA

    - name: Display Image Tag in GitHub Actions summary
      run: |
        echo "### ✅ CI/CD complete" >> $GITHUB_STEP_SUMMARY
        echo "Image pushed: \`$IMAGE_NAME:$SHORT_SHA\`" >> $GITHUB_STEP_SUMMARY
